teamSettings:
    # Define the maximum number of team that can be created during the game. this number should be superior to 3 and inferior to 11
    maxNumberOfTeam: 4
    # Define how many players can join a single team when this team has no upgrade.
    initialTeamSize: 10
    # List bellow the different materials that could be asked for tribute to join a team.
    teamJoiningTribute:
      requiredMaterials:
      - WOOL
      - LOG
      - COBBLESTONE
      - IRON_INGOT
      - EMERALD
      # List bellow the price for all those materials for each team
      BLUE:
        WOOL: 1
        LOG: 64
        COBBLESTONE: 64
        IRON_INGOT: 10
      RED:
        WOOL: 1
        LOG: 128
        COBBLESTONE: 64
      DEFAULT:
        WOOL: 32
        LOG: 64
        DIAMOND: 10
        IRON_INGOT: 32
        EMERALD: 1
    # List bellow the different materials that could be asked for tribute to create a team.
    teamCreatingTribute:
      requiredMaterials:
        - EMERALD
        - DIAMOND
        - LOG
      VALUES:
        EMERALD: 128
        DIAMOND: 128
        LOG: 256



baseSettings:
    # Define the first influence radius of a normal base.
    initialRadius: 50
    # Define the influence bonus for the first base (HeadQuarter) of a team.
    radiusHQBonus: 25
    # Define the average distance between the first spawn of the map and a random barbarian spawn location.
    # Minimum value: 100
    barbariansSpawnDistance: 1
    # Define the minimum distance between a team HQ and another team's base
    # The formula in use is: (initialRadius + radiusHQBonus)*BaseMinHQDistanceToOthers
    # Minimum value: 2
    BaseMinHQDistanceToOthers: 4
    # Define the minimum distance between a team base and the basic map spawn
    # The formula in use is: initialRadius*BaseMinDistance
    BaseMinDistanceToSpawn: 10
    baseInitialCost:
      requiredMaterials:
      - WOOL
      - LOG
      - EMERALD
      - DIAMOND
      VALUES:
        WOOL: 6
        LOG: 6
        EMERALD: 10
        DIAMOND: 10
