main: com.github.lolopasdugato.mcwarclan.MCWarClan
name: MCWarClan
version: 0.1
author: Eldorabe
description: This plugin allows you and your friend to create a battle between many teams.

database: false

commands:
 showteams:
  description: List all teams in the game.
  aliases: [lt, st]
  permission: mcwarclan.showteams
  usage: Type /<command> to list all teams in the game.
 team:
  description: List all players in your team.
  permission: mcwarclan.team
  usage: Type /<command> (playername) to list players that are in your (or player's) team.
 assign:
  description: Assign a player to a team.
  permission: mcwarclan.assign
  usage: Type /<command> [playername] & [teamname | teamcolor] to switch a player to a team.
 unassign:
  description: Unassign a player from a team.
  permission: mcwarclan.unassign
  usage: Type /<command> [playername] to unassign someone to a team.
 join:
  description: Makes you join a team.
  permission: mcwarclan.join
  usage: Type /<command> [teamname | teamcolor] to join a team.
 leave:
  description: Makes you leave a team.
  permission: mcwarclan.leave
  usage: Type /<command> to leave your team and join Barbarians.
 createteam:
  description: Allows you to create a new team.
  permission: mcwarclan.createteam
  usage: Type /<command> [teamname] && [teamcolor] to create the new team.
 createhq:
  description: Allows you to create the team HeadQuarter.
  permission: mcwarclan.createhq
  usage: Type /<command> [basename] to create the new base.
 createbase:
  description: Allows you to create a base. The base reference is the base from where the plugin will start to find a place in the given direction.
  permission: mcwarclan.createbase
  usage: Type /<command> [basename] & [base reference id] & [north | south | east | west]
 baseinfo:
  description: Depending on how you call the function, it will give you information about a base. Without any argument, it will give you information of the base you are currently in.
  permission: mcwarclan.baseinfo
  usage: Type /<command> (base id | all)
 contest:
  description: Allows you to launch a battle to capture an enemy base. Before the capture process begin, destroy the enemy flag.
  permission: mcwarclan.contest
  usage: Type /<command> in an enemy base to launch the capture process. Don't forget to break the flag to launch the process properly !
 upgrade:
  description: Allows a player to upgrade a particular base by standing into this base or by specifying its ID.
  permission: mcwarclan.upgrade
  usage: Type /<command> (base id)
 savemoney:
  description: Allows a player to store a certain amount of money into the team treasure.
  permission: mcwarclan.savemoney
  usage: Type /<command> [amount]
 withdraw:
  description: Allows a player to take emeralds from the team treasure. These emeralds will appear in the base he is currently in.
  permission: mcwarclan.withdraw
  usage: Type /<command> [amount]
 treasure:
  description: Allows a player to see the treasure owned by his team.
  permission: mcwarclan.treasure
  usage: Type /<command> to see the treasure your team owns.
 showrights:
   description: List all the rights you have depending on your role.
   aliases: [sr]
   permission: mcwarclan.showrights
   usage: Type /<command> to list all your rights.
permissions:
 mcwarclan.*:
  description: Gives access to all MCWarClan commands.
  children:
   mcwarclan.showteams: true
   mcwarclan.team: true
   mcwarclan.assign: true
   mcwarclan.unassign: true
   mcwarclan.join: true
   mcwarclan.leave: true
   mcwarclan.createteam: true
   mcwarclan.createhq: true
   mcwarclan.createbase: true
   mcwarclan.baseinfo: true
   mcwarclan.contest: true
   mcwarclan.upgrade: true
   mcwarclan.savemoney: true
   mcwarclan.withdraw: true
 mcwarclan.showteams:
  description: List all teams in the game.
  default: true
 mcwarclan.team:
  description: List all players in your team.
  default: true
 mcwarclan.assign:
  description: Assign a player to a team.
  default: false
 mcwarclan.unassign:
  description: Unassign a player from a team.
  default: false
 mcwarclan.join:
  description: Makes you join a team.
  default: true
 mcwarclan.leave:
  description: Makes you leave your team.
  default: true
 mcwarclan.createteam:
  description: Allows you to create a new team.
  default: true
 mcwarclan.createhq:
  description: Allows you to create the team HeadQuarter.
  default: true
 mcwarclan.createbase:
  description: Allows you to create a base.
  default: true
 mcwarclan.baseinfo:
  description: Allows you to see information about your team bases.
  default: true
 mcwarclan.contest:
  description: Allows you to launch a battle to capture an enemy base.
  default: true
 mcwarclan.upgrade:
  description: Allows a player to upgrade a particular base by standing into this base or by specifying its ID.
  default: true
 mcwarclan.savemoney:
  description: Allows a player to store a certain amount of money into the team treasure.
  default: true
 mcwarclan.withdraw:
  description: Allows a player to take emeralds from the team treasure. These emeralds will appear in the base he is currently in.
  default: true
 mcwarclan.showrights:
  description: List all the rights you have depending on your role.
  default: true